name: 'demo-infra'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=d3m0P@ssw0rd!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" 
      - "10001:10001" 
      - "10002:10002" 
    volumes:
      - azurite_data:/data
      - ./azurite:/workspace
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mssql_data:
  redis_data:
  azurite_data:
